### ISSUE TITLE
Enforce Async Method Naming

### ISSUE THREAD

**Issue by ardalis** [ardalis/EditorConfig#1]
I tried this but it doesn't seem to work - https://github.com/dotnet/roslyn/issues/40050

Is there a set of editorconfig settings that will create warnings if you don't name your async methods (returning Task or Task<T>) with the `Async` suffix?

**Comment by Kamyab7** [comment]
Hi @ardalis, I hope you're doing well. Thanks for creating such a nice editorconfig.
According to this [article](https://medium.com/@asad99/enforcing-async-method-naming-convention-using-editorconfig-in-visual-studio-829d358edb28) and this [repository](https://github.com/asadul99/naming-rule/blob/master/.editorconfig), I fix this issue hope you find it useful.
